FROM node:18

ARG PORT
ARG SALT_ROUNDS
ARG API_VERSION
ARG JWT_SECRET
ARG JWT_EXPIRATION_TIME
ARG DB_TYPE
ARG DB_HOST
ARG DB_PORT
ARG DB_USERNAME
ARG DB_PASSWORD
ARG DB_DATABASE
ARG MAIL_HOST
ARG MAIL_PORT
ARG EMAIL
ARG MAIL_PASSWORD
ARG PGADMIN_DEFAULT_EMAIL
ARG PGADMIN_DEFAULT_PASSWORD

ENV PORT=${PORT}
ENV SALT_ROUNDS=${SALT_ROUNDS}
ENV API_VERSION=${API_VERSION}
ENV JWT_SECRET=${JWT_SECRET}
ENV JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
ENV DB_TYPE=${DB_TYPE}
ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_DATABASE=${DB_DATABASE}
ENV MAIL_HOST=${MAIL_HOST}
ENV MAIL_PORT=${MAIL_PORT}
ENV EMAIL=${EMAIL}
ENV MAIL_PASSWORD=${MAIL_PASSWORD}
ENV PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
ENV PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm i copyfiles

RUN npm run build

RUN ls -al /app/dist

CMD [ "npm", "run", "start:prod" ]