# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Hoặc branch bạn muốn triển khai

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Bước 2: Đăng nhập vào Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Bước 3: Build và Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker compose build
          docker tag big-ledger-app 0339637721/big-ledger-app:latest
          docker push 0339637721/big-ledger-app:latest

      # Bước 4: SSH vào EC2 và Deploy
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /path/to/your/app
            git pull origin main  # Nếu bạn có repository trên EC2
            docker-compose pull
            docker-compose up -d
